# Generated by Django 5.2 on 2025-09-02 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.couple')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('invited_count', models.IntegerField()),
                ('confirmed_count', models.IntegerField()),
                ('rsvp_status', models.CharField(max_length=20)),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('response_status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('couple_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.couple')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.group')),
            ],
        ),
    ]
