# Generated by Django 5.2 on 2025-09-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_alter_group_group_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='response_date',
        ),
        migrations.AlterField(
            model_name='guest',
            name='confirmed_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='invited_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='guest',
            name='response_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='guest',
            name='rsvp_status',
            field=models.CharField(default='not_sent', max_length=20),
        ),
    ]
