# Generated by Django 5.2 on 2025-09-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_remove_guest_response_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='response_status',
            field=models.CharField(blank=True, default='pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='rsvp_status',
            field=models.CharField(blank=True, default='not_sent', max_length=20, null=True),
        ),
    ]
