# Generated by Django 5.2.5 on 2025-09-03 13:26

import expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color_code',
            field=models.CharField(default=expenses.models.generate_random_color, max_length=7),
        ),
    ]
